### PR TITLE
Fix yosys-plugin extract syntax

### LINKED ISSUE #6: Churchroad-yosys `write_lakeroad` command yields incorrect syntax?
Inside `churchroad.cc`, [here](https://github.com/uwsampl/churchroad/blob/c21f241975687ba1d6cf598322fcea2667e95e35/yosys-plugin/churchroad.cc#L1389) and [here](https://github.com/uwsampl/churchroad/blob/c21f241975687ba1d6cf598322fcea2667e95e35/yosys-plugin/churchroad.cc#L1407) I think Churchroad's producing egglog code of the form `(Extract hi lo Expr)`, when it should be `((Op1 (Extract high low) expr)` as defined in [lakeroad.egg](https://github.com/uwsampl/churchroad/blob/c21f241975687ba1d6cf598322fcea2667e95e35/egglog_src/lakeroad.egg#L23). 

Getting Egglog to try and parse the former results in an `Arity mismatch, expected 2 args: (Extract 8 8 v0)`.

### PR DESCRIPTION
**Pull request by ninehusky**
Closes #6 .

### CODE REVIEW

**Comment by ninehusky** [comment]
@gussmith23 looks like CI is failing because of a [permission related issue](https://github.com/uwsampl/churchroad/actions/runs/7996744826/job/21839843054?pr=7#step:5:421)?

**Comment by gussmith23** [comment]
Just re-ran CI, unsure what is going on with that error and I'm hoping it's just spurious (but it's probably not)

**Comment by gussmith23** [comment]
Something is going wrong with the `GITHUB_TOKEN` permissions when you specifically are triggering the workflow. The workflow specifically requests write permissions on packages. When the workflow is triggered by me, we see this:

image

But when you trigger:

image


Will keep debugging.

**Comment by ninehusky** [comment]
Closed by #10 .

**Pull request closed without merging**
